### ISSUE TITLE
Invalid collection view URL

### ISSUE THREAD

**Issue by f-picca** [jheddings/notes2notion#1]
Hello, 
I'm trying to import my notes into Notion, but after cloning the repo and setting it up accordingly to the instructions in readme, I'm stuck with this error:

`Traceback (most recent call last):
  File "/Users/fabriziopicca/Development/notes2notion/main.py", line 67, in <module>
    tracker = logbook.ImportLog(client, conf['import_log_url'])
  File "/Users/fabriziopicca/Development/notes2notion/logbook.py", line 23, in __init__
    view = client.get_collection_view(url)
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 163, in get_collection_view
    raise Exception("Invalid collection view URL")
Exception: Invalid collection view URL`

I guess there's something wrong in the log configuration (I created a top level page named Log and pasted the link in the config file). Am I doing something wrong here?

**Comment by f-picca** [comment]
Sorry, I just understood the problem. The page for the log should be a table (I was using a plain page).
