### ISSUE TITLE
ValueError badly formed hexadecimal UUID String

### ISSUE THREAD

**Issue by bchewy** [jheddings/notes2notion#2]
```
python3 main.py --config notes2notion.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/notion/utils.py", line 37, in extract_id
    return str(uuid.UUID(url_or_id))
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianchew/Desktop/notes2notion/notes2notion/main.py", line 65, in <module>
    top_page = client.get_block(conf['import_page_url'])
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 117, in get_block
    block_id = extract_id(url_or_id)
  File "/usr/local/lib/python3.9/site-packages/notion/utils.py", line 39, in extract_id
    raise InvalidNotionIdentifier(input_value)
notion.utils.InvalidNotionIdentifier: ARCHIVE_PAGE_URL
```

Any idea what this is?

**Comment by jheddings** [comment]
It looks like something changed in the API and is returning unexpected data to the unofficial API client...  I need to take a look at the public API and see if it has enough capability to use that.  I'll try to get to that "soon"

**Comment by jheddings** [comment]
It looks like you still need to edit the config file and set (or comment out) the `import_page_url` option...  That said, I am not sure this will continue to work with the unofficial Notion API client.  I need to get it switched over to the new client "soon".
