### ISSUE TITLE
Not Reading Apple Notes Data

### ISSUE THREAD

**Issue by andrewcincotta** [jheddings/notes2notion#5]
[andrew@Andrews-MacBook-Pro` notes2notion % python3 main.py --config notes2notion.yaml
Processing - Christmas List
Traceback (most recent call last):
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/main.py", line 92, in <module>
    page = builder.build(note)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/builder.py", line 102, in build
    page = pdoc.parse(note["body"])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 45, in parse
    self.process(soup)
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 71, in process
    if self.parse_elem(child, parent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 157, in parse_elem
    pfunc(elem, parent)
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 191, in parse_div
    self.process(elem, parent)
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 71, in process
    if self.parse_elem(child, parent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 157, in parse_elem
    pfunc(elem, parent)
  File "/Users/andrew/Documents/Scripting/Python/notes2notion-main/notes2notion/parser.py", line 203, in parse_h2
    block = blocks.Heading2.from_text(text)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Heading2' has no attribute 'from_text'

**Comment by jheddings** [comment]
Confirmed.  I need to update the version of `notional` to fix this...  I'll try to get that done ASAP.

**Comment by andrewcincotta** [comment]
> Confirmed. I need to update the version of `notional` to fix this... I'll try to get that done ASAP.

Appreciate it!

**Comment by andrewcincotta** [comment]
> Confirmed. I need to update the version of `notional` to fix this... I'll try to get that done ASAP.

Could it be that I used notional 2.0? I tried installing everything according to requirements.txt, but I couldn't find notional 0.1.2

**Comment by jheddings** [comment]
Yeah...  I changed the interface in a more recent version of Notional.  I had already stated updating this script, so hopefully it shouldn't take too much longer to get it sorted out.
